version: "2"
services: 
 mongodatabase:
  image: "mongo"
  container_name: "mongo_db_usermgmt"
  ports: 
   - "27010:27017"
  volumes:
   - database-mongodata:/data/db
  healthcheck:
   test: echo 'db.stats().ok' | mongo ${DBURL} --quiet
   interval: 5s
   timeout: 5s
   retries: 12
  restart: always
    
 nodeapp:
  container_name: "node_app_usermgmt"
  # build: 
    # context: .
    # dockerfile: Dockerfile
  image: shravankb/ums-app:latest
  environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DBURL=${DBURL}
  depends_on: 
    - mongodatabase
  # env_file: 
    # - .env.production
  links:
   - mongodatabase
volumes:
   database-mongodata: