
//!---------------------------------STATUS CODES----------------------------

const STATUS_CODES = {
//HTTP Sucess Codes
SUCCESS : 200,
CREATED : 201,
NO_CONTENT : 204, //update and deleted
RESET_CONTENT : 206, // reset the document / refresh the UI 

//HTTP Client Error Codes
BAD_REQUEST : 400,
UNAUTHORIZED : 401,
FORBIDDEN : 403,
NOT_FOUND : 404,
CONFLICT : 409,
GONE : 410,
UNPROCESSABLE_ENTITY : 422,
INTERNAL_SERVER_ERROR : 500,
UNKNOWN_ERROR : 500,

}

//!----------------------------------ERROR MESSAGES----------------------------------------------

const ERROR_TYPES = {
    FORBIDDEN: 'FORBIDDEN',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    BAD_REQUEST: 'ValidationError',
    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',
    UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
    GONE: 'GONE'    
};

const ERROR_MESSAGES = {
    ERR_FORBIDDEN: 'ERR FORBIDDEN',
    ERR_INTERNAL_SERVER_ERROR: 'ERR_INTERNAL_SERVER_ERROR',
    ERR_UNAUTHORIZED: 'ERR_UNAUTHORIZED',
    ERR_BAD_REQUEST: 'ERR_BAD_REQUEST',
    ERR_NOT_FOUND: 'ERR_NOT_FOUND',
    ERR_CONFLICT: 'ERR_CONFLICT',
    ERR_UNPROCESSABLE_ENTITY: 'ERR_UNPROCESSABLE_ENTITY',
    MSG_MISSING_PARAMS: 'MSG_MISSING_PARAMS',
    ERR_USER_ALREADY_EXIST: 'ERR_USER_ALREADY_EXIST',
    ERR_USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
    ERR_INVALID_PASSWORD: 'ERR_INVALID_PASSWORD',
    ERR_INVALID_INPUT: 'ERR_INVALID_INPUT',
};


module.exports={
    
    STATUS_CODES,
    
    ERROR_MESSAGES,

    ERROR_TYPES

}
